export const VERIFICATION = {
    RESEND_VERIFICATION: 'RESEND_VERIFICATION',
    RESEND_VERIFICATION_ERROR: 'RESEND_VERIFICATION_ERROR',
    RESEND_VERIFICATION_SUCCESS: 'RESEND_VERIFICATION_SUCCESS',
};
