export const PROFILE = {
    CREATE_PROFILE: 'CREATE_PROFILE',
    CREATE_PROFILE_ERROR: 'CREATE_PROFILE_ERROR',
    CREATE_PROFILE_SUCCESS: 'CREATE_PROFILE_SUCCESS',
};

export const BVN = {
    VERIFIY_BVN: 'VERIFY_BVN',
    VERIFIY_BVN_ERROR: 'VERIFY_BVN_ERROR',
    VERIFIY_BVN_SUCCESS: 'VERIFY_BVN_SUCCESS',
};
