export const ORDERS = {
    GET_ALL_ORDERS: 'GET_ALL_ORDERS',
    GET_ALL_ORDERS_ERROR: 'GET_ALL_ORDERS_ERROR',
    GET_ALL_ORDERS_SUCCESS: 'GET_ALL_ORDERS_SUCCESS',
};

export const INVOICE = {
    DELETE_INVOICE: 'DELETE_INVOICE',
    DELETE_INVOICE_ERROR: 'DELETE_INVOICE_ERROR',
    DELETE_INVOICE_SUCCESS: 'DELETE_INVOICE_SUCCESS',
    GET_ALL_INVOICE: 'GET_ALL_INVOICE',
    GET_ALL_INVOICE_ERROR: 'GET_ALL_INVOICE_ERROR',
    GET_ALL_INVOICE_SUCCESS: 'GET_ALL_INVOICE_SUCCESS',
};

export const USERS = {
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_ALL_USERS_ERROR: 'GET_ALL_USERS_ERROR',
    GET_ALL_USERS_SUCCESS: 'GET_ALL_USERS_SUCCESS',
};

export const ADMIN_ORDER = {
    ADMIN_CREATE_ORDER: 'ADMIN_CREATE_ORDER',
    ADMIN_CREATE_ORDER_ERROR: 'ADMIN_CREATE_ORDER_ERROR',
    ADMIN_CREATE_ORDER_SUCCESS: 'ADMIN_CREATE_ORDER_SUCCESS',
};

