export const PROPERTY = {
    CLEAN_PROPERTY: 'CLEAN_PROPERTY',
    GET_PROPERTY: 'GET_PROPERTY',
    GET_PROPERTY_ERROR: 'GET_PROPERTY_ERROR',
    GET_PROPERTY_SUCCESS: 'GET_PROPERTY_SUCCESS',
};

export const ORDER = {
    CREATE_ORDER: 'CREATE_ORDER',
    CREATE_ORDER_ERROR: 'CREATE_ORDER_ERROR',
    CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
};
