export const PROPERTIES = {
    GET_PROPERTIES: 'GET_PROPERTIES',
    GET_PROPERTIES_ERROR: 'GET_PROPERTIES_ERROR',
    GET_PROPERTIES_SUCCESS: 'GET_PROPERTIES_SUCCESS',
    SEARCH_PROPERTIES: 'SEARCH_PROPERTIES',
};
