export const USER_ORDERS = {
    GET_USER_ORDERS: 'GET_USER_ORDERS',
    GET_USER_ORDERS_ERROR: 'GET_USER_ORDERS_ERROR',
    GET_USER_ORDERS_SUCCESS: 'GET_USER_ORDERS_SUCCESS',
};

export const INVOICES = {
    CLEAN_INVOICE: 'CLEAN_INVOICE',
    GET_INVOICE: 'GET_INVOICE',
    GET_INVOICE_ERROR: 'GET_INVOICE_ERROR',
    GET_INVOICE_SUCCESS: 'GET_INVOICE_SUCCESS',
    GET_USER_INVOICES: 'GET_USER_INVOICES',
    GET_USER_INVOICES_ERROR: 'GET_USER_INVOICES_ERROR',
    GET_USER_INVOICES_SUCCESS: 'GET_USER_INVOICES_SUCCESS',
};
