export const POSTS = {
    GET_POSTS: 'GET_POSTS',
    GET_POSTS_ERROR: 'GET_POSTS_ERROR',
    GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
    SEARCH_POSTS: 'SEARCH_POSTS',
};

export const POST = {
    GET_POST: 'GET_POST',
    GET_POST_ERROR: 'GET_POST_ERROR',
    GET_POST_SUCCESS: 'GET_POST_SUCCESS',
    REMOVE_POST: 'REMOVE_POST',
};
