export const LOGIN = {
    LOGIN_USER: 'LOGIN_USER',
    LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
};

export const AUTH_USER = {
    GET_AUTH_USER: 'GET_AUTH_USER',
    GET_AUTH_USER_ERROR: 'GET_AUTH_USER_ERROR',
    GET_AUTH_USER_SUCCESS: 'GET_AUTH_USER_SUCCESS',
    SET_AUTH_STATE: 'SET_AUTH_STATE',
};

export const PASSWORD = {
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    FORGOT_PASSWORD_ERROR: 'FORGOT_PASSWORD_ERROR',
    FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
    RESET_PASSWORD: 'RESET_PASSWORD',
    RESET_PASSWORD_ERROR: 'RESET_PASSWORD_ERROR',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
};

export const LOGOUT = {
    LOGOUT_USER: 'LOGOUT_USER',
    LOGOUT_USER_ERROR: 'LOGOUT_USER_ERROR',
    LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS',
};
